export const sampleQuizAnswers = {
  name: 'Ayush',
  city: 'Lucknow',
  state: 'Uttar Pradesh',
  household: '3',
  transportMode: 'bus',
  dailyKm: 10,
  flightsPerYear: '1-2',
  diet: 'pure_veg',
  eatingOut: 'Rarely',
  foodWaste: 'Minimal (We repurpose leftovers)',
  lpgCylinders: '4-6',
  electricityUnits: 200,
  acHours: '1-3 hours',
  inverter: 'no',
  onlineOrders: '2-5',
  newClothes: '1-2 items',
  wasteManagement: 'composted',
};
